name: Run ls Command

on:
  push:
    branches:
      - Child1
  pull_request:
    branches:
      - master 
jobs:
  run-ls:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (needed to access files in the repo)
      - name: Checkout code
        uses: actions/checkout@v3


