name: Run ls Command

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  run-ls:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (needed to access files in the repo)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the 'ls' command
      - name: List files
        run: ls -lah

      - name: Display PR Number
        run: echo "The PR number is ${{ github.event.pull_request.number }}"
